version: '3'

services:
  mongo:
    image: healthcheck/mongo
    ports:
      - 27017:27017

  api:
    restart: on-failure
    build: ./packages/music-ico-api
    volumes:
      - .:/usr/src/app
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 5500:5500

  watcher:
    restart: on-failure
    build: ./packages/music-ico-watcher
    volumes:
      - .:/usr/src/app
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo


